### get user role by id:
GET http://localhost:8080/api/v1/users/1/roles
Authorization: Basic oshani02 Tur-abh123

###create user
POST http://localhost:8080/api/v1/signup
Content-Type: application/json

{
  "username": "user",
  "email": "user@soccerin.com",
  "password": "User-user123",
  "profileLogoUrl":"https://cdn.pixabay.com/photo/2013/07/13/11/44/penguin-158551_1280.png"
}